apiVersion: v2
name: node-goat
description: A Helm chart for OWASP NodeGoat
type: application
version: 0.1.0
appVersion: "1.50.0"
keywords:
  - owasp
  - nodejs
  - demo
maintainers:
  - name: Roshan Kadasani
home: https://github.com/rkfrog/node-goat
dependencies: []
