apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-node-goat
  labels:
    {{- include "node-goat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "node-goat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "node-goat.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: {{ .Values.podSecurityContext.hostNetwork }}
      hostPID: {{ .Values.podSecurityContext.hostPID }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: node-goat
          image: {{ include "node-goat.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: host-root
              mountPath: /host
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: host-root
          hostPath:
            path: /
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
