name: "Frogbot Security Scan"

on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
  security-events: write

jobs:
  pr-security-scan:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    env:
      JF_GIT_API_ENDPOINT: https://api.github.com
    # JF_GIT_API_ENDPOINT: 'https://HOSTNAME/api/v3' # for Github self hosted
      JF_GIT_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
      JF_GIT_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
      JF_URL: https://${{ secrets.JF_URL }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JF_GIT_REPO: ${{ github.event.repository.name }}
      JF_GIT_OWNER: ${{ github.repository_owner }}
      JF_GIT_PROVIDER: 'github'
      JFROG_CLI_LOG_LEVEL: "DEBUG"
      CI: "TRUE"
    steps:
      - name: Download Frogbot V3
        run: |
          curl -fSL \
            -o frogbot \
            "https://releases.jfrog.io/artifactory/frogbot/v3/3.1.3/frogbot-linux-amd64/frogbot"
          chmod +x frogbot
          ./frogbot scan-pull-request

  repository-scan:
    # if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    0n:
      workflow_dispatch:
      schedule:
        # The repository will be scanned once a day at 00:00 GMT.
        - cron: "0 3 * * *"
    runs-on: devf-dind-amd-scale-set # ubuntu-latest
    env:
      JF_GIT_API_ENDPOINT: https://api.github.com
    # JF_GIT_API_ENDPOINT: 'https://HOSTNAME/api/v3' # for Github self hosted
      JF_GIT_BASE_BRANCH: ${{ github.ref_name }}
      JF_URL: https://${{ secrets.JF_URL }}
      JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JF_GIT_PROVIDER: 'github'
      JF_GIT_OWNER: ${{ github.repository_owner }}
      JF_GIT_REPO: ${{ github.event.repository.name }}
      JFROG_CLI_LOG_LEVEL: "DEBUG"
      CI: "TRUE"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Download and run Frogbot V3
        run: |
          curl -fSL \
            -o frogbot \
            "https://releases.jfrog.io/artifactory/frogbot/v3/3.1.3/frogbot-linux-amd64/frogbot"
          chmod +x frogbot
          ./frogbot scan-repository